### ISSUE TITLE
Merge with systray-rs

### ISSUE THREAD

**Issue by tinywombat765** [thatsmydoing/rustray#1]
There is another library currently for rust to make system stray icons that is trying to be cross platform [systray-rs](https://github.com/qdot/systray-rs) but it is lacking a Linux implementation.  I though you might be interested in a some point merging your code into that library.

**Comment by thatsmydoing** [comment]
While contributing to that project does seem interesting, our projects are not the same.

systray-rs is a library that lets programs put an icon on a systray. rusttray on the other hand is an application that implements a systray that those programs can put icons in. It's more along the lines of [stalonetray](http://stalonetray.sourceforge.net/).

**Comment by tinywombat765** [comment]
My mistake.  Thank you.
